### PR TITLE
feat: select history item by press 'Enter' key.

### PR DESCRIPTION
**Pull request by debuggerx01**
当按下回车键，且焦点不在删除按钮上时，执行选择剪切板历史并关闭UI逻辑，效果与双击选择一致

Log: 一个社区里呼声很高的需求：回车选择剪切板历史记录

### CODE REVIEW

**Comment by debuggerx01** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by debuggerx01** [comment]
any help?

**Comment by waterlovemelon** [comment]
That's a good idea, i'll add some people to discuss it.

**Comment by kegechen** [comment]
1. 提交整理一下，有4个commit，还有冲突
2. commit 不够规范。可以参考历史提交中的格式， 标题+空行+内容

**Comment by debuggerx01** [comment]
#126

**Comment by debuggerx01** [comment]
#126 @kegechen

**Pull request closed without merging**
